name: Build Edge Module

on:
  push:
    branches:
    - main
    paths:
    - 'src/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: levi106/videoanalyzer

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: |
          onlatest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          
    - name: Build and push to GitHub Container Registry
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./src/
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ./src/Dockerfile.amd64
        push: ${{ github.event_name != 'pull_request' }}
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
